ByteNestBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #lets us append to the url pattern
from django.conf.urls.static import static 
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),#includes urls from articles app
    path('about/',views.about),
    path('',article_views.article_list,name="Home"),
    path('accounts/',include('accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'    

urlpatterns = [
    path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout')
]

articles/urls.py
from django.urls import path
from . import views

app_name= 'articles'

urlpatterns = [
    path('',views.article_list,name="list"),
    path('create/',views.article_create,name="create"),
    path('<slug:slug>/',views.article_detail,name="detail"), 
    
    
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)  
    slug  = models.SlugField()
    body  = models.TextField()
    date  = models.DateTimeField(auto_now_add=True) # when an article is created it is automatically populate this field
    thumb = models.ImageField(default='default.png',blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
   
    
    def __str__(self) : # displays the string representation of fields
        return self.title
    
    def snippet(self):
        return self.body[0:70]+'....' # displays only 50 characters on the article page and .... in the end

articles/forms.py
from django import forms
from . import models

#this is where we define model forms
class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields=['title','body','slug','thumb']

ByteNestBlog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    return render(request,'homepage.html')
    # return HttpResponse('home')

def about (request):
    return render (request,'about.html')
    # return HttpResponse('about')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid(): # checks if the value inserted by user is correct and meets requirement or not
         form.save() #creates a new user for us and returns it to us
         user = form.save()
         login(request,user)
         return redirect('articles:list') #name of the app is article tha we defined and the list is the name of the url that we defined as well
    else:
        form = UserCreationForm()
    return render (request,'accounts/signup.html',{'form':form})#the third parameter is s dict where the vlaue is the variable we just created

def login_view(request):
    if request.method == 'POST':
        form= AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log user in
            user = form.get_user() #retriving the user
            login(request,user) #logging the user in
            if 'next' in request.POST:
                return redirect (request.POST.get('next'))
            else:
                return redirect("articles:list")
    
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method== 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles}) #django looks in templates and finds article folder 

def article_detail(request,slug):
   # return HttpResponse(slug)
   article= Article.objects.get(slug=slug)
   return render(request,'articles/article_detail.html',{'article':article})


@login_required(login_url="/accounts/login/") #this decorator is protecting this view function from firing
def article_create(request):
    if request.method == 'POST':
      form = forms.CreateArticle(request.POST,request.FILES)  
      if form.is_valid:
          #save article to the database
          instance=form.save(commit=False) #commit false means "dont save just yet , let me don something with that value"
          instance.author= request.user #attches the author thats logged in to the instance
          instance.save() #commiting the save 
          return redirect('articles:list')
    else:
        form= forms.CreateArticle()
        return render(request,'articles/article_create.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{%block content%}
    <h2>Login<h2>
     <form class="site-form" action= "/accounts/login/" method="post"> {% comment %} action means where to submit the data gotten from post {% endcomment %}
        {% csrf_token %}
        {{form}} {% comment %} this is the key of the dic we made in views.py {% endcomment %}
        {%if request.GET.next %}
            <input type="hidden" name= "next" value = "{{request.GET.next}}">
        {% endif %}
        <input type ="submit" value ="login">
    </form>

{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{%block content%}
    <h2>Signup<h2>
     <form class="site-form" action= "/accounts/signup/" method="post"> {% comment %} action means where to submit the data gotten from post {% endcomment %}
        {% csrf_token %}
        {{form}} {% comment %} this is the key of the dic we made in views.py {% endcomment %}
        <input type ="submit" value ="signup">
    </form>
{%endblock%}

articles/templates/articles/article_create.html
{% extends 'base_layout.html'%}

{% block content %}
<div class ="create-article">
    <h2>Create a new article</h2>
     <form class="site-form" action ="{%url 'articles:create' %}" method ="post" enctype="multipart/form-data"> {% comment %} we need enctype whenver we upload file {% endcomment %}
        {% csrf_token %}
        {{form}}
        <input type ="submit" value="create">
    </form>
</div>

{%endblock%}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src ="{{article.thumb.url}}"/>
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
 {% extends 'base_layout.html'%}
    
 {%block content%}
     <h1>Articles List<h1>
     <div class="articles">
       {% for article in articles%}
        <div class"article">
            <h6> <a href="{% url 'articles:detail' article.slug %}">{{article.title}}</a><h6>
            <p>{{article.snippet}}</p>
            <p>{{article.date}}</p>
        </div>
     {%endfor %}
    </div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>About</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>hmm<h1>
        <h2>This is the About page<h2>
        <p>We like to talk ?<p>
        <script src="" async defer></script>
    </body>
</html>

templates/base_layout.html
{% comment %} this is the base html layout which is in every page so it makes sense to make it constant and only change the content in the midddle rather than putting header and footer from stratch {% endcomment %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Articles</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'styles.css'%}">
    </head>
    <body>
      <header class="wrapper"> 
        <h1><a href="{% url 'Home'%}"><img src="{%static 'logo.png'%}"/></a></h1> 
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class ="logout-link" action="{%url 'accounts:logout'%}" method="post">
                        {%csrf_token%}
                        <button type ="submit">Logout</button>
                    </form>
                </li>
                <li>
                    <a href="{%url 'articles:create' %}" class ="highlight">New Article
                    </a>
                </li>
                {%else%}
                <li>
                    <a href="{%url 'accounts:login' %}">Login
                    </a>
                </li>
                <li>
                    <a href="{%url 'accounts:signup' %}">Signup
                    </a>
                </li>
                {% endif%}
            </ul>
    </header>
        {%block content%}
        {% endblock%}
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       <h1>This is the Homepage<h1>
        <p> Welcome to ByteNestBlog<p>
        <script src="" async defer></script>
    </body>
</html>